# Generated by Django 3.2.7 on 2021-11-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pawsupuser',
            options={'verbose_name': 'User'},
        ),
    ]
