# Generated by Django 3.2.7 on 2021-11-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0012_alter_service_verified_status'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.service',),
        ),
        migrations.CreateModel(
            name='ServicePurchaseRecord',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.servicepurchaserecord',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.pawsupuser',),
        ),
    ]
