# Generated by Django 3.2.7 on 2021-11-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcards', '0007_auto_20211014_2003'),
        ('PawsUpAdmin', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='PetCard',
            fields=[
            ],
            options={
                'verbose_name': 'Pet Card',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('petcards.petcard',),
        ),
        migrations.AlterModelOptions(
            name='servicepurchaserecord',
            options={'verbose_name': 'Service Purchase Record'},
        ),
    ]
