# Generated by Django 3.2.7 on 2021-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('num_of_ratings', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, upload_to='')),
            ],
        ),
    ]
