# Generated by Django 3.2.7 on 2021-11-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpurchaserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchaserecord',
            name='address',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='productImages/'),
        ),
    ]
