# Generated by Django 3.2.7 on 2021-11-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_verified_status'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTemp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.service',),
        ),
    ]
