# Generated by Django 3.2.7 on 2021-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcard',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petcard',
            name='spayed_or_neutered',
            field=models.BooleanField(default=False),
        ),
    ]
