# Generated by Django 3.2.7 on 2021-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcards', '0003_remove_petcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcard',
            name='owner',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
