# Generated by Django 3.2.7 on 2021-10-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcards', '0002_auto_20211007_0303'),
        ('petcards', '0004_petcard_owner'),
    ]

    operations = [
    ]
