# Generated by Django 3.2.7 on 2021-10-15 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petcards', '0006_remove_petcard_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petcard',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='petcard',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
