# Generated by Django 3.2.7 on 2021-11-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0014_auto_20211105_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingService',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('service.service',),
        ),
    ]
