# Generated by Django 3.2.7 on 2021-11-03 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0012_alter_service_verified_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVerificationFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
