# Generated by Django 3.2.7 on 2021-10-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('pet_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(default=0)),
                ('owner_id', models.IntegerField(default=0)),
                ('service_type', models.CharField(max_length=100)),
                ('service_start', models.DateTimeField()),
                ('service_end', models.DateTimeField()),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=40)),
                ('details', models.CharField(max_length=250)),
                ('facilityList', models.CharField(max_length=100)),
                ('checkInNotes', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=None)),
                ('paypal_id', models.IntegerField(default=0)),
                ('pricingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.price')),
            ],
        ),
    ]
