# Generated by Django 3.2.7 on 2021-10-14 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_alter_price_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pricingList',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_id',
        ),
        migrations.AddField(
            model_name='price',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='paypal_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
