# Generated by Django 3.2.7 on 2021-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20211013_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_start',
            field=models.TimeField(),
        ),
    ]
