# Generated by Django 3.2.7 on 2021-10-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20211014_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='paypal_id',
            field=models.CharField(max_length=100),
        ),
    ]
