# Generated by Django 3.2.7 on 2021-10-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_paypal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='num_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
