# Generated by Django 3.2.7 on 2021-10-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_num_of_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payoutID', models.IntegerField(default=0)),
            ],
        ),
    ]
