# Generated by Django 3.2.7 on 2021-10-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_num_of_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='facilityList',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
