# Generated by Django 3.2.7 on 2021-10-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_facilitylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='verified_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
