# Generated by Django 3.2.7 on 2021-10-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_facilitylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='addService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=20)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
