# Generated by Django 3.2.7 on 2021-10-29 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0009_merge_0007_payoutid_0008_addservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='PriceQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('service_purchase_record', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.servicepurchaserecord')),
            ],
        ),
        migrations.CreateModel(
            name='addServiceQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('service_purchase_record', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.servicepurchaserecord')),
            ],
        ),
    ]
