# Generated by Django 3.2.7 on 2021-11-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_verified_status'),
        ('service', '0010_addservicequantity_pricequantity_servicepurchaserecord'),
    ]

    operations = [
    ]
