# Generated by Django 3.2.7 on 2021-11-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_merge_20211101_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='verified_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
