# Generated by Django 3.2.7 on 2021-11-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_service_verified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepurchaserecord',
            name='approval_time',
            field=models.DateTimeField(default='1000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='service',
            name='checkInNotes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='details',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
